@startuml
autoactivate on
GestorHotel -> GestorHotel: agregarReservaSimple(...datos)
GestorHotel -> Hotel : getHabitacionSimpleDistonibles(fecha)
Hotel--> GestorHotel : lista habitaciones
GestorHotel -> ReservaA: <<create>>
ReservaA -> ReservaA:Reserva(habitacion, cliente)
ReservaA -> ClienteA: agregarReserva(ReservaA)
ClienteA -> ClienteA: calcularEstado()
alt es habitual
ClienteA -> ClienteA: setEstadoHabitual
else no es habitual
ClienteA -> ClienteA: setEstadoEsporadico
end
ReservaA -> HabitacionA: reservar()
ReservaA --> GestorHotel : referencia a ReservaA
@enduml